// Generated by CoffeeScript 1.6.2
(function() {
  var GImage, GInputEvent, GMap, OverlayCanvasController, ViewController, isMobileSafari, tick, viewcontroller,
    __slice = [].slice;

  GImage = (function() {
    function GImage(location, owner) {
      var me;

      if (location == null) {
        location = 'broken.png';
      }
      this.image = new Image();
      this.image.src = "game/images/" + location;
      me = this;
      this.image.onload = function() {
        return me.onload();
      };
      this.loaded = false;
      this.owner = owner;
    }

    GImage.prototype.onload = function() {
      this.loaded = true;
      if ((this.owner != null) && (this.owner.imageLoaded != null)) {
        return this.owner.imageLoaded();
      }
    };

    return GImage;

  })();

  GMap = (function() {
    function GMap(location) {
      var me;

      this.loaded = false;
      this.map = [];
      me = this;
      $.getScript("game/maps/" + location + ".js");
      if (location != null) {
        $.get("game/maps/" + location + ".map", function(r) {
          me.loaded = true;
          return me.map = JSON.parse(r);
        });
      } else {
        this.newMap();
      }
    }

    GMap.prototype.newMap = function(x, y) {
      var i, j, _i, _j;

      if (x == null) {
        x = 10;
      }
      if (y == null) {
        y = 10;
      }
      this.map = Array(y);
      for (i = _i = 0; _i <= y; i = _i += 1) {
        this.map[i] = Array(x);
        for (j = _j = 0; _j <= x; j = _j += 1) {
          this.map[i][j] = {
            sprite: 33
          };
        }
      }
      return this.loaded = true;
    };

    return GMap;

  })();

  isMobileSafari = function() {
    return navigator.userAgent.match(/(iPod|iPhone|iPad)/) && navigator.userAgent.match(/AppleWebKit/);
  };

  GInputEvent = (function() {
    function GInputEvent() {
      var data, type;

      type = arguments[0], data = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      this.type = type;
      switch (this.type) {
        case 'K':
          this.key = data[0];
          this.shift = data[1];
          break;
        case 'M':
          this.x = data[0];
          this.y = data[1];
          break;
        case 'D':
          this.dir = data[0];
      }
    }

    GInputEvent.prototype.toText = function() {
      var char, shift, textstring;

      textstring = '';
      switch (this.type) {
        case 'K':
          char = String.fromCharCode(this.key);
          shift = '';
          if ((this.shift != null) && this.shift) {
            shift = ' + SHIFT ';
          }
          textstring = "Keyboard event: key number " + this.key + " " + shift + " (which is '" + char + "')";
          break;
        case 'M':
          textstring = "Mouse click at (" + this.x + ", " + this.y + ")";
          break;
        case 'D':
          textstring = "D-pad cilcked (" + this.dir + ")";
          break;
        default:
          textstring = "Input type " + this.type;
      }
      return textstring;
    };

    return GInputEvent;

  })();

  OverlayCanvasController = (function() {
    function OverlayCanvasController(text) {
      var i, line1, line2, _i;

      this.relinquishcontrol = false;
      this.readytofinish = false;
      this.line1 = text;
      this.line2 = '';
      this.text = text;
      this.count = 0;
      if (text.length > 18) {
        for (i = _i = 0; _i <= 18; i = _i += 1) {
          if (text[18 - i] === ' ') {
            line1 = text.slice(0, +i + 1 || 9e9);
            line2 = text.slice(i);
            alert("Okay...");
            break;
          }
        }
      }
    }

    OverlayCanvasController.prototype.dialog = function(line1, line2) {
      viewcontroller.context.drawImage(viewcontroller.images['overlay.png'].image, 50, 450);
      viewcontroller.context.fillStyle = 'black';
      viewcontroller.context.textBaseline = 'middle';
      viewcontroller.context.textAlign = 'left;';
      viewcontroller.context.fillText(this.line1, 95, 520);
      return viewcontroller.context.fillText(this.line2, 95, 575);
    };

    OverlayCanvasController.prototype.tick = function() {
      var i, line1_now, line2_now, _i, _len, _ref;

      _ref = viewcontroller.inputstack;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        switch (i) {
          case "A":
            if (this.readytofinish) {
              this.relinquishcontrol = true;
            }
        }
      }
      this.count++;
      line1_now = this.line1.slice(0, +(this.count / 3) + 1 || 9e9);
      if ((this.count / 3) - line1_now.length > 0) {
        line2_now = this.line2.slice(0, +(this.count / 3 - line1_now.length) + 1 || 9e9);
      } else {
        line2_now = '';
      }
      if (this.count / 3 < this.text.length + 1) {
        return this.dialog(line1_now, line2_now);
      } else if (this.count % 12 === 0) {
        this.readytofinish = true;
        return viewcontroller.renderSprite(32 + this.count % 24, 7.8, 7.2);
      }
    };

    return OverlayCanvasController;

  })();

  ViewController = (function() {
    function ViewController(selector) {
      var me;

      if (selector == null) {
        selector = "pokeCanvas";
      }
      this.canvas = $("#" + selector).get(0);
      this.context = this.canvas.getContext('2d');
      this.context.font = '30px "Pokemon GB"';
      if (isMobileSafari()) {
        this.context.font = '45px "Courier"';
      }
      this.images = [];
      this.map = [];
      this.stack = [];
      this.timestep = 30;
      this.inputstack = [];
      this.dpad_touchstate = [];
      me = this;
      $(this.canvas).mousedown(function(e) {
        return me.canvasinput_mouseClick(e.pageX, e.pageY);
      });
      $(document).keypress(function(e) {
        e.preventDefault();
        return me.inputstack.push(new GInputEvent('K', e.keyCode, e.shiftKey));
      });
      $('#dpad > div').bind('touchstart', this.canvasinput_Dpad_down);
      $('#dpad > div').mousedown(this.canvasinput_Dpad_down);
      $('#dpad > div').bind('touchend', this.canvasinput_Dpad_up);
      $('#dpad > div').mouseup(this.canvasinput_Dpad_up);
    }

    ViewController.prototype.ready = function() {
      var a, b, _i, _j, _len, _len1, _ref;

      _ref = [this.images, this.map];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        a = _ref[_i];
        for (_j = 0, _len1 = a.length; _j < _len1; _j++) {
          b = a[_j];
          if ((b[a].loaded == null) || !b[a].loaded) {
            return false;
          }
        }
      }
      return true;
    };

    ViewController.prototype.loadImages = function() {
      var a, list, _i, _len;

      list = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        a = list[_i];
        this.images[a] = new GImage(a, this);
      }
      return true;
    };

    ViewController.prototype.loadMap = function(location) {
      this.map = new GMap(location);
      return true;
    };

    ViewController.prototype.renderSprite = function(i, x, y) {
      return this.context.drawImage(this.images['spritesheet.png'].image, 112 * (i % 16), Math.floor(i / 16) * 112, 112, 112, x * 75, y * 75, 75, 75);
    };

    ViewController.prototype.imageLoaded = function() {
      return true;
    };

    ViewController.prototype.canvasinput_mouseClick = function(x, y) {
      x = Math.floor(x - $(this.canvas).offset().left / 20);
      y = Math.floor(y - $(this.canvas).offset().left / 20);
      return this.inputstack.push(new GInputEvent('M', x, y));
    };

    ViewController.prototype.canvasinput_Dpad_down = function(e) {
      var DEvent, direction;

      direction = '';
      switch (this.id) {
        case 'dpad_u':
          direction = 'U';
          break;
        case 'dpad_l':
          direction = 'L';
          break;
        case 'dpad_r':
          direction = 'R';
          break;
        case 'dpad_d':
          direction = 'D';
      }
      DEvent = new GInputEvent('D', direction);
      viewcontroller.inputstack.push(DEvent);
      return viewcontroller.dpad_touchstate = DEvent;
    };

    ViewController.prototype.canvasinput_Dpad_up = function(e) {
      return viewcontroller.dpad_touchstate = 0;
    };

    ViewController.prototype.tick = function() {
      if (!this.ready()) {
        return alert("Not ready yet...");
      }
      this.stack[0].tick();
      return true;
    };

    return ViewController;

  })();

  viewcontroller = new ViewController;

  viewcontroller.loadImages('spritesheet.png', 'overlay.png', 'npc.png', 'minimenu_top.png', 'minimenu_bottom.png');

  viewcontroller.loadMap('lecturehall');

  viewcontroller.stack.push(new OverlayCanvasController('Hello, world!'));

  document.viewcontroller = viewcontroller;

  tick = function() {
    viewcontroller.tick();
    return setTimeout(tick, viewcontroller.timestep);
  };

  tick();

}).call(this);
