// Generated by CoffeeScript 1.6.2
var BuyMenuController;

BuyMenuController = (function() {
  function BuyMenuController() {
    var coral_files, f, fish_files, _i, _j, _len, _len1;

    fish_files = sync_get('game/assets/glob.php?type=fish');
    fish_files = JSON.parse(fish_files);
    this.fishes = [];
    for (_i = 0, _len = fish_files.length; _i < _len; _i++) {
      f = fish_files[_i];
      this.fishes.push(new Fish(f));
    }
    coral_files = sync_get('game/assets/glob.php?type=coral');
    coral_files = JSON.parse(coral_files);
    this.corals = [];
    for (_j = 0, _len1 = coral_files.length; _j < _len1; _j++) {
      f = coral_files[_j];
      this.corals.push(new Coral(f));
    }
    this.refresh();
  }

  BuyMenuController.prototype.refresh = function() {
    var a, desc, html, _i, _len, _ref;

    html = "";
    _ref = this.fishes.concat(this.corals);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      a = _ref[_i];
      desc = "This item has no description whatsoever.";
      if (a.description != null) {
        desc = a.description;
      }
      html += this.buymenu_mediaObject({
        image: a.image,
        title: a.name,
        text: desc
      });
    }
    return $("#buy").html(html);
  };

  BuyMenuController.prototype.buymenu_mediaObject = function(content) {
    var retval;

    retval = "<div class='span3'><div class='media'><a class='pull-left' href='#'>				  <img class='media-object' style='width: 64px' src='game/images/" + content.image + "'>				  </a><div class='media-body'><h4 class='media-heading'>" + content.title + "</h4>				  	" + content.text + "</div></div></div>";
    return retval;
  };

  return BuyMenuController;

})();
