// Generated by CoffeeScript 1.6.2
var BuyMenuController;

BuyMenuController = (function() {
  function BuyMenuController() {
    var a, coral_files, f, fish_files, machine_files, unique, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref;

    fish_files = sync_get('game/assets/glob.php?type=fish');
    fish_files = JSON.parse(fish_files);
    this.fishes = [];
    for (_i = 0, _len = fish_files.length; _i < _len; _i++) {
      f = fish_files[_i];
      this.fishes.push(new Fish(f));
    }
    coral_files = sync_get('game/assets/glob.php?type=coral');
    coral_files = JSON.parse(coral_files);
    this.corals = [];
    for (_j = 0, _len1 = coral_files.length; _j < _len1; _j++) {
      f = coral_files[_j];
      this.corals.push(new Coral(f));
    }
    machine_files = sync_get('game/assets/glob.php?type=machines');
    machine_files = JSON.parse(machine_files);
    this.machines = [];
    for (_k = 0, _len2 = machine_files.length; _k < _len2; _k++) {
      f = machine_files[_k];
      this.machines.push(new Machine(f));
    }
    this.refresh();
    _ref = this.fishes.concat(this.corals, this.machines);
    for (_l = 0, _len3 = _ref.length; _l < _len3; _l++) {
      a = _ref[_l];
      unique = md5(a.filename);
      $("#buythis" + unique).data('jsonfile', a.filename).data('type', a.type).click(function() {
        return document.tool = new BuyTool($(this).data('jsonfile'), $(this).data('type'), document.tool);
      });
    }
  }

  BuyMenuController.prototype.refresh = function() {
    var a, desc, html, _i, _len, _ref;

    html = "";
    _ref = this.fishes.concat(this.corals, this.machines);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      a = _ref[_i];
      desc = "This item has no description whatsoever.";
      if (a.description != null) {
        desc = a.description;
      }
      html += this.buymenu_mediaObject({
        image: a.image,
        title: a.name,
        text: desc,
        unique: md5(a.filename)
      });
    }
    return $("#buy").html(html);
  };

  BuyMenuController.prototype.buymenu_mediaObject = function(content) {
    var retval;

    retval = "<div class='span3' style='height: 150px;'><div class='media'><a class='pull-left' id='buythis" + content.unique + "' href='#'>				  <img class='media-object' style='width: 64px' src='game/images/" + content.image + "'>				  </a><div class='media-body'><h4 class='media-heading'>" + content.title + "</h4>				  	" + content.text + "</div></div></div>";
    return retval;
  };

  return BuyMenuController;

})();
