// Generated by CoffeeScript 1.6.2
var Coral;

Coral = (function() {
  function Coral(filename) {
    this.filename = filename;
    this.coral_raw = sync_get('game/assets/coral/' + filename);
    if (this.coral_raw.name == null) {
      alert("Illegal coral \"" + filename + "\"");
    }
    this.image = this.coral_raw.image;
    viewcontroller.loadImages(this.image);
    this.position = {
      x: 0,
      y: 0
    };
    this.scale = 0.2;
  }

  Coral.prototype.tick = function() {
    return viewcontroller.renderSprite(this.image, this.position.x, this.position.y, this.scale);
  };

  return Coral;

})();
