// Generated by CoffeeScript 1.6.2
var Coral;

Coral = (function() {
  function Coral(image) {
    this.image = image;
    viewcontroller.loadImages(image);
    this.position = {
      x: 0,
      y: 0
    };
  }

  Coral.prototype.tick = function() {
    return viewcontroller.renderSprite(this.image, this.position.x, this.position.y, 0.2);
  };

  return Coral;

})();
