// Generated by CoffeeScript 1.6.2
var FishTankCanvasController;

FishTankCanvasController = (function() {
  function FishTankCanvasController() {
    this.relinquishcontrol = false;
    this.readytofinish = false;
    this.count = 0;
    this.fishes = [];
    this.fishes.push(new Fish('clown-fish.png'));
  }

  FishTankCanvasController.prototype.tick = function() {
    var a, _i, _len, _ref;

    viewcontroller.renderSprite('TankBackground.jpg', 0, 0);
    _ref = this.fishes;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      a = _ref[_i];
      a.tick();
    }
    return true;
  };

  return FishTankCanvasController;

})();
