// Generated by CoffeeScript 1.6.2
var isMobileSafari, md5, sync_get,
  _this = this;

isMobileSafari = function() {
  return navigator.userAgent.match(/(iPod|iPhone|iPad)/) && navigator.userAgent.match(/AppleWebKit/);
};

sync_get = function(file) {
  var done, retval;

  retval = '';
  done = function(result) {
    return retval = result;
  };
  jQuery.ajax({
    url: file,
    success: done,
    async: false
  });
  return retval;
};

md5 = function(string) {
  return hex_md5(string);
};
