// Generated by CoffeeScript 1.6.2
var calculate_difference, calculate_distance, isMobileSafari, md5, sync_get,
  _this = this;

isMobileSafari = function() {
  return navigator.userAgent.match(/(iPod|iPhone|iPad)/) && navigator.userAgent.match(/AppleWebKit/);
};

sync_get = function(file) {
  var done, retval;

  retval = '';
  done = function(result) {
    return retval = result;
  };
  jQuery.ajax({
    url: file,
    success: done,
    async: false
  });
  return retval;
};

md5 = function(string) {
  return hex_md5(string);
};

calculate_distance = function(a, b) {
  if (b == null) {
    b = {
      x: 0,
      y: 0
    };
  }
  return Math.sqrt((a.x - b.x) * (a.x - b.x) + (a.y - b.y) * (a.x - b.x));
};

calculate_difference = function(a, b) {
  var ex, why;

  ex = a.x - b.x;
  why = a.y - b.y;
  return {
    x: ex,
    y: why
  };
};
