// Generated by CoffeeScript 1.6.2
var Tank;

Tank = (function() {
  function Tank(image) {
    this.image = image;
    this.temperature = 75;
    this.salt = 0;
    this.supply = 100;
    this.waste = 0;
    viewcontroller.loadImages(image);
  }

  Tank.prototype.tick = function() {
    viewcontroller.renderSprite('TankBackground.jpg', 0, 0, 1.2);
    $("#tank_supply").css('width', this.supply + '%');
    $("#tank_salt").css('width', this.salt + '%');
    $("#tank_waste").css('width', this.waste + '%');
    return $("#tank_temperature").css('width', ((this.temperature - 45) * (20 / 9)) + '%');
  };

  return Tank;

})();
