// Generated by CoffeeScript 1.6.2
var SpongeTool, WarmTool;

WarmTool = (function() {
  function WarmTool(image) {
    this.image = image;
    if (image != null) {
      viewcontroller.loadImages(image);
    }
  }

  WarmTool.prototype.click = function() {
    return true;
  };

  WarmTool.prototype.hold = function() {
    if (typeof image !== "undefined" && image !== null) {
      viewcontroller.renderSprite(this.image, 0, 0, 1.2);
    }
    return document.tank.temperature += 0.2;
  };

  return WarmTool;

})();

SpongeTool = (function() {
  function SpongeTool(image) {
    this.image = image;
    if (image != null) {
      viewcontroller.loadImages(image);
    }
    $();
  }

  SpongeTool.prototype.click = function() {
    return true;
  };

  SpongeTool.prototype.hold = function() {
    if (typeof image !== "undefined" && image !== null) {
      viewcontroller.renderSprite(this.image, 0, 0, 1.2);
    }
    return document.tank.waste -= 0.2;
  };

  return SpongeTool;

})();
