// Generated by CoffeeScript 1.6.2
var SpongeTool, WarmTool;

WarmTool = (function() {
  function WarmTool(image) {
    this.image = image;
    if (image != null) {
      viewcontroller.loadImages(image);
    }
  }

  WarmTool.prototype.click = function() {
    return true;
  };

  WarmTool.prototype.hold = function() {
    if (typeof image !== "undefined" && image !== null) {
      viewcontroller.renderSprite(this.image, 0, 0, 1.2);
    }
    return document.tank.temperature += 0.2;
  };

  return WarmTool;

})();

SpongeTool = (function() {
  function SpongeTool(image) {
    this.image = image;
    this.scale = 0.6;
    if (this.image != null) {
      viewcontroller.loadImages(this.image);
    }
  }

  SpongeTool.prototype.click = function(x, y) {
    return this.hold(x, y);
  };

  SpongeTool.prototype.hold = function(x, y) {
    if (this.image != null) {
      viewcontroller.renderSprite(this.image, x - this.scale * viewcontroller.images[this.image].image.width / 2, y - this.scale * viewcontroller.images[this.image].image.height / 2, this.scale);
    }
    return document.tank.waste -= 2;
  };

  return SpongeTool;

})();
