// Generated by CoffeeScript 1.6.2
var tick, viewcontroller;

viewcontroller = new ViewController;

viewcontroller.loadImages('TankBackground.jpg');

viewcontroller.stack.push(new FishTankCanvasController());

document.viewcontroller = viewcontroller;

$(function() {
  document.tools = [];
  document.tools['sponge'] = new SpongeTool('sponge3.png');
  return document.tool = document.tools['sponge'];
});

tick = function() {
  viewcontroller.tick();
  return setTimeout(tick, viewcontroller.timestep);
};

tick();
